FONT_FAMILY = "Segoe UI"

TITLE = (FONT_FAMILY, 24, "bold")
SUBTITLE = (FONT_FAMILY, 18, "bold")
HEADING = (FONT_FAMILY, 14, "bold")
BODY = (FONT_FAMILY, 13)
BODY_BOLD = (FONT_FAMILY, 13, "bold")
CAPTION = (FONT_FAMILY, 11)
EMOJI_LARGE = (FONT_FAMILY, 48)
EMOJI_SMALL = (FONT_FAMILY, 20)
PERCENTAGE = (FONT_FAMILY, 12, "bold")
